version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: servidor_java
    depends_on:
      - rabbitmq
      - api
    volumes:
      - ./server/data:/data

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: client_web
    ports:
      - "8080:8080"
    depends_on:
      - api
      - server